### ISSUE TITLE
How to autogenerate _id for a document

### ISSUE THREAD

**Issue by frenchbread** [zalando/esio#21]
### How to autogenerate `_id` value for a document? 

Just like [here](https://www.elastic.co/guide/en/elasticsearch/guide/current/index-doc.html#_autogenerating_ids).

I've tried `esio:put(Sock, "urn:es:mqt:analytics", Log).` and got an error - `{error,400}`

**Comment by fogfish** [comment]
Hello,

Thanks you for your report. The issue has been fixed at `0.1.1` version of library and it is available at master branch.

Please consider that Erlang has better alternatives then Elastic Search auto generate _id. There is an implementation of k-ordereding schemas. There are available to get globally unique id. 

https://github.com/fogfish/uid
https://github.com/boundary/flake
 
Best Regards
