### ISSUE TITLE
Unable to build a project with esio as a dependency

### ISSUE THREAD

**Issue by frenchbread** [zalando/esio#24]
I'm using `esio` as a dependency in [this](https://github.com/apinf/emq_plugin_apinf) project.

While building the project, i'm getting following stack trace:

```
❯ make
 GEN    rebar.config
 GEN    rebar.config
 ERLC   chord.erl datum.erl datum_benchmark.erl heap.erl lens.erl category.erl datum_macro.erl partial.erl m_error.erl m_id.erl m_io.erl m_state.erl monad.erl deq.erl q.erl ring.erl sbf.erl stream.erl bst.erl htree.erl rbtree.erl
src/monad.erl: no such file or directory
make[4]: *** [ebin/datum.app] Error 1
make[3]: *** [app] Error 2
make[2]: *** [deps] Error 2
make[1]: *** [deps] Error 2
make: *** [deps] Error 2
```

Removing `esio` from deps list allows the build to pass.

What could be a reason for this and how to fix it?

**Comment by fogfish** [comment]
Wow, I see that you works together with  Konstantin.  Say hello to him we use to work together ;-) I am surprised this world is too small.

The issue is erlang.mk. It is not able to build a new file structure of one of dependencies (datum).
I am investigating an issue... No quick solution yet. I'd recommend to switch into `rebar3`

**Comment by fogfish** [comment]
You need to use datum version 3.4.2  as quick, short-term "hack" solution but long-term either erlang.mk needs to be fixed or rebar3 is used. 
```
{datum, ".*", 
   {git, "https://github.com/fogfish/datum", {tag, '3.4.2'}}
}
```
From my side, I'll look if I can improve the file structure of datum library and make it compatible with erlang.mk but you might reach erlang.mk owner to fix the issue.

**Comment by frenchbread** [comment]
@fogfish Yes, but I have not met Konstantin personally.

Downgrading to `v3.4.2` let the build to pass. Thanks 👍

**Comment by fogfish** [comment]
Good! Glad to hear it but this is a temporary patch. I might need to "debug" erlang.mk or find some other solution. I'll get you posted here.
