### ISSUE TITLE
Please consider switching to rebar3

### ISSUE THREAD

**Issue by phanimahesh** [zalando/esio#26]
Currently esio uses rebar for building, which has been officially deprecated in favor of rebar3. rebar3 has many important improvements, my favorite being lockfile support to enable reproducible builds. Can esio please switch to recommending and using rebar3.

Only tweaks needed are removing rebar.lock from gitignore (I'm not sure why it was ignored in the first place), and linking to rebar3 instead of rebar from the README. The existing rebar config works with rebar3 unmodified. I'll happily send a PR if that's okay.

**Comment by fogfish** [comment]
Thank you for comments! The project is managed using rebar3. 
https://github.com/zalando/esio/blob/master/Makefile#L29

I think you got confusion due to README.md

**Comment by phanimahesh** [comment]
Thanks!
