### ISSUE TITLE
What is the best approach to mock-up ElasticSearch

### ISSUE THREAD

**Issue by fogfish** [zalando/esio#4]
Unit test need to validate the implementation is compatible with Elastic Search DSL. Elastic Search is a backing service from deployment perspective. It is possible to mock up a local stub using HTTP with static json files but this would not validate correctness of i/o operation.

**Comment by LappleApple** [comment]
Hey @fogfish, want to label "Help Wanted"? Want to start a conversation about this with Poirot?

**Comment by fogfish** [comment]
Help is appreciate on this subject. I've not progressed to much. There is a strong need to "validate" query protocol and its compatibility with Elastic Search. Once issue is resolve we can integrate testing as part of travis builds.

**Comment by LappleApple** [comment]
Let's also move this to the Incubator until it's future is more certain. Is that OK?

**Comment by fogfish** [comment]
You'll break all dependent libraries if you move project away. As I said, it has been used by some communities. The functional side of this project is good.. Only minor issue needs to be resolved.

**Comment by LappleApple** [comment]
@fogfish You can transfer projects from one repo to another and it will redirect (does not count for what's in Git). We do this all the time.

Let's figure out how to promote this project more widely, then. What would be your first step?

**Comment by fogfish** [comment]
Are you 100% confident that redirect works with rebar3 and erlang.mk? Basically, they execute git clone under-the-hood. 

About promotion...  This is a pure "driver" project / connectivity layer to elastic search. Lately, I've got detached from ElasticSearch (you know the reason).  We are starting to use Elastic Search again... I'am planning one short story about Elastic Search 5.0 vs AWS. Let's use it as promotion stage. If you have better options about advertisement of "driver" projects, I am open on it.

**Comment by LappleApple** [comment]
[From GitHub](https://help.github.com/articles/transferring-a-repository/#redirects-and-git-remotes).

The best way to grow this project is to get more people working on it. That's where I'd start. :)

**Comment by fogfish** [comment]
>
> However, to avoid confusion, we strongly recommend updating any existing local clones to point to the new repository URL.
>

Exactly, what I mean... You transfer and all (1.5) users are impacted...
